apiVersion: v1
kind: Service
metadata:
  name: frontend-nginx-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:elasticloadbalancing:ap-northeast-2:703131122346:loadbalancer/net/aeb007da1d6294b8fa3f02178fc1e79b/f87f8909d2f937fc
spec:
  selector:
    app: frontend-nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 80
  type: LoadBalancer





